const KEYS_MAP = {
  Backquote: [true, '`', '~', 'ё', 'Ё'],
  Digit1: [true, '1', '!', '1', '!'],
  Digit2: [true, '2', '@', '2', '"'],
  Digit3: [true, '3', '#', '3', '№'],
  Digit4: [true, '4', '$', '4', ';'],
  Digit5: [true, '5', '%', '5', '%'],
  Digit6: [true, '6', '^', '6', ':'],
  Digit7: [true, '7', '&', '7', '?'],
  Digit8: [true, '8', '*', '8', '*'],
  Digit9: [true, '9', '(', '9', '('],
  Digit0: [true, '0', ')', '0', ')'],
  Minus: [true, '-', '_', '-', '_'],
  Equal: [true, '=', '+', '=', '+'],
  Backspace: [false, 'Backspace', 'Backspace', 'Backspace', 'Backspace'],
  Tab: [false, 'Tab', 'Tab', 'Tab', 'Tab'],

  KeyQ: [true, 'q', 'Q', 'й', 'Й'],
  KeyW: [true, 'w', 'W', 'ц', 'Ц'],
  KeyE: [true, 'e', 'E', 'у', 'У'],
  KeyR: [true, 'r', 'R', 'к', 'К'],
  KeyT: [true, 't', 'T', 'е', 'Е'],
  KeyY: [true, 'y', 'Y', 'н', 'Н'],
  KeyU: [true, 'u', 'U', 'г', 'Г'],
  KeyI: [true, 'i', 'I', 'ш', 'Ш'],
  KeyO: [true, 'o', 'O', 'щ', 'Щ'],
  KeyP: [true, 'p', 'P', 'з', 'З'],
  BracketLeft: [true, '[', '{', 'х', 'Х'],
  BracketRight: [true, ']', '}', 'ъ', 'Ъ'],
  Backslash: [true, '\\', '|', '\\', '/'],
  Delete: [false, 'Del', 'Del', 'Del', 'Del'],
  CapsLock: [false, 'Caps    ', 'Caps    ', 'Caps    ', 'Caps    '],

  KeyA: [true, 'a', 'A', 'ф', 'Ф'],
  KeyS: [true, 's', 'S', 'ы', 'Ы'],
  KeyD: [true, 'd', 'D', 'в', 'В'],
  KeyF: [true, 'f', 'F', 'а', 'А'],
  KeyG: [true, 'g', 'G', 'п', 'П'],
  KeyH: [true, 'h', 'H', 'р', 'Р'],
  KeyJ: [true, 'j', 'J', 'о', 'О'],
  KeyK: [true, 'k', 'K', 'л', 'Л'],
  KeyL: [true, 'l', 'L', 'д', 'Д'],
  Semicolon: [true, ';', ':', 'ж', 'Ж'],
  Quote: [true, '\'', '"', 'э', 'Э'],
  Enter: [false, 'Enter       ', 'Enter       ', 'Enter       ', 'Enter       '],
  ShiftLeft: [false, 'Shift           ', 'Shift          ', 'Shift           ', 'Shift           '],

  KeyZ: [true, 'z', 'Z', 'я', 'Я'],
  KeyX: [true, 'x', 'X', 'ч', 'Ч'],
  KeyC: [true, 'c', 'C', 'с', 'С'],
  KeyV: [true, 'v', 'V', 'м', 'М'],
  KeyB: [true, 'b', 'B', 'и', 'И'],
  KeyN: [true, 'n', 'N', 'т', 'Т'],
  KeyM: [true, 'm', 'M', 'ь', 'Ь'],
  Comma: [true, ',', '<', 'б', 'Б'],
  Period: [true, '.', '>', 'ю', 'Ю'],
  Slash: [true, '/', '?', '.', ','],
  ShiftRight: [false, '⇧', '⇧', '⇧', '⇧'],
  ArrowUp: [false, '↑', '↑', '↑', '↑'],
  Language: [false, 'EN', 'EN', 'RU', 'RU'],

  ControlLeft: [false, 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  MetaLeft: [false, 'Win', 'Win', 'Win', 'Win'],
  AltLeft: [false, 'Alt', 'Alt', 'Alt', 'Alt'],
  Space: [false, 'Space', 'Space', 'Space', 'Space'],
  AltRight: [false, 'Alt', 'Alt', 'Alt', 'Alt'],
  ControlRight: [false, 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ArrowLeft: [false, '←', '←', '←', '←'],
  ArrowDown: [false, '↓', '↓', '↓', '↓'],
  ArrowRight: [false, '→', '→', '→', '→'],
};

const KEYBOARD_KEYS = [
  'Backquote',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Minus',
  'Equal',
  'Backspace',
  'Tab',

  'KeyQ',
  'KeyW',
  'KeyE',
  'KeyR',
  'KeyT',
  'KeyY',
  'KeyU',
  'KeyI',
  'KeyO',
  'KeyP',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'Delete',
  'CapsLock',

  'KeyA',
  'KeyS',
  'KeyD',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyJ',
  'KeyK',
  'KeyL',
  'Semicolon',
  'Quote',
  'Enter',
  'ShiftLeft',

  'KeyZ',
  'KeyX',
  'KeyC',
  'KeyV',
  'KeyB',
  'KeyN',
  'KeyM',
  'Comma',
  'Period',
  'Slash',
  'ShiftRight',
  'ArrowUp',
  'Language',

  'ControlLeft',
  'MetaLeft',
  'AltLeft',
  'Space',
  'AltRight',
  'ControlRight',
  'ArrowLeft',
  'ArrowDown',
  'ArrowRight',
];

// const KEYS_MAP = [
//   { Backquote: ['`', '~', 'ё', 'Ё'] },
//   { Digit1: ['1', '!', '1', '!'] },
//   { Digit2: ['2', '@', '2', '"'] },
//   { Digit3: ['3', '#', '3', '№'] },
//   { Digit4: ['4', '$', '4', ';'] },
//   { Digit5: ['5', '%', '5', '%'] },
//   { Digit6: ['6', '^', '6', ':'] },
//   { Digit7: ['7', '&', '7', '?'] },
//   { Digit8: ['8', '*', '8', '*'] },
//   { Digit9: ['9', '(', '9', '('] },
//   { Digit0: ['0', ')', '0', ')'] },
//   { Minus: ['-', '_', '-', '_'] },
//   { Equal: ['=', '+', '=', '+'] },
//   { Backspace: false },
//   { Tab: false },

//   { KeyQ: ['q', 'Q', 'й', 'Й'] },
//   { KeyW: ['w', 'W', 'ц', 'Ц'] },
//   { KeyE: ['e', 'E', 'у', 'У'] },
//   { KeyR: ['r', 'R', 'к', 'К'] },
//   { KeyT: ['t', 'T', 'е', 'Е'] },
//   { KeyY: ['y', 'Y', 'н', 'Н'] },
//   { KeyU: ['u', 'U', 'г', 'Г'] },
//   { KeyI: ['i', 'I', 'ш', 'Ш'] },
//   { KeyO: ['o', 'O', 'щ', 'Щ'] },
//   { KeyP: ['p', 'P', 'з', 'З'] },
//   { BracketLeft: ['[', '{', 'х', 'Х'] },
//   { BracketRight: [']', '}', 'ъ', 'Ъ'] },
//   { Backslash: ['\\', '|', '\\', '/'] },
//   { Delete: false },
//   { CapsLock: false },

//   { KeyA: ['a', 'A', 'ф', 'Ф'] },
//   { KeyS: ['s', 'S', 'ы', 'Ы'] },
//   { KeyD: ['d', 'D', 'в', 'В'] },
//   { KeyF: ['f', 'F', 'а', 'А'] },
//   { KeyG: ['g', 'G', 'п', 'П'] },
//   { KeyH: ['h', 'H', 'р', 'Р'] },
//   { KeyJ: ['j', 'J', 'о', 'О'] },
//   { KeyK: ['k', 'K', 'л', 'Л'] },
//   { KeyL: ['l', 'L', 'д', 'Д'] },
//   { Semicolon: [';', ':', 'ж', 'Ж'] },
//   { Quote: ['\'', '"', 'э', 'Э'] },
//   { Enter: false },
//   { ShiftLeft: false },

//   { KeyZ: ['z', 'Z', 'я', 'Я'] },
//   { KeyX: ['x', 'X', 'ч', 'Ч'] },
//   { KeyC: ['c', 'C', 'с', 'С'] },
//   { KeyV: ['v', 'V', 'м', 'М'] },
//   { KeyB: ['b', 'B', 'и', 'И'] },
//   { KeyN: ['n', 'N', 'т', 'Т'] },
//   { KeyM: ['m', 'M', 'ь', 'Ь'] },
//   { Comma: [',', '<', 'б', 'Б'] },
//   { Period: ['.', '>', 'ю', 'Ю'] },
//   { Slash: ['/', '?', '.', ','] },
//   { ArrowUp: false },
//   { Language: false },

//   { ControlLeft: false },
//   { MetaLeft: false },
//   { AltLeft: false },
//   { Space: false },
//   { AltRight: false },
//   { ControlRight: false },
//   { ArrowLeft: false },
//   { ArrowDown: false },
//   { ArrowRight: false },
// ];

export {
  KEYS_MAP,
  KEYBOARD_KEYS,
};
