const KEYS_MAP = {
  Backquote: [true, '`', '~', 'ё', 'Ё', false],
  Digit1: [true, '1', '!', '1', '!', false],
  Digit2: [true, '2', '@', '2', '"', false],
  Digit3: [true, '3', '#', '3', '№', false],
  Digit4: [true, '4', '$', '4', ';', false],
  Digit5: [true, '5', '%', '5', '%', false],
  Digit6: [true, '6', '^', '6', ':', false],
  Digit7: [true, '7', '&', '7', '?', false],
  Digit8: [true, '8', '*', '8', '*', false],
  Digit9: [true, '9', '(', '9', '(', false],
  Digit0: [true, '0', ')', '0', ')', false],
  Minus: [true, '-', '_', '-', '_', false],
  Equal: [true, '=', '+', '=', '+', false],
  Backspace: [false, 'Backspace', 'Backspace', 'Backspace', 'Backspace', false],
  Tab: [false, 'Tab', 'Tab', 'Tab', 'Tab', false],

  KeyQ: [true, 'q', 'Q', 'й', 'Й', false],
  KeyW: [true, 'w', 'W', 'ц', 'Ц', false],
  KeyE: [true, 'e', 'E', 'у', 'У', false],
  KeyR: [true, 'r', 'R', 'к', 'К', false],
  KeyT: [true, 't', 'T', 'е', 'Е', false],
  KeyY: [true, 'y', 'Y', 'н', 'Н', false],
  KeyU: [true, 'u', 'U', 'г', 'Г', false],
  KeyI: [true, 'i', 'I', 'ш', 'Ш', false],
  KeyO: [true, 'o', 'O', 'щ', 'Щ', false],
  KeyP: [true, 'p', 'P', 'з', 'З', false],
  BracketLeft: [true, '[', '{', 'х', 'Х', false],
  BracketRight: [true, ']', '}', 'ъ', 'Ъ', false],
  Backslash: [true, '\\', '|', '\\', '/', false],
  Delete: [false, 'Del', 'Del', 'Del', 'Del', false],
  CapsLock: [false, 'Caps    ', 'Caps    ', 'Caps    ', 'Caps    ', false],

  KeyA: [true, 'a', 'A', 'ф', 'Ф', false],
  KeyS: [true, 's', 'S', 'ы', 'Ы', false],
  KeyD: [true, 'd', 'D', 'в', 'В', false],
  KeyF: [true, 'f', 'F', 'а', 'А', false],
  KeyG: [true, 'g', 'G', 'п', 'П', false],
  KeyH: [true, 'h', 'H', 'р', 'Р', false],
  KeyJ: [true, 'j', 'J', 'о', 'О', false],
  KeyK: [true, 'k', 'K', 'л', 'Л', false],
  KeyL: [true, 'l', 'L', 'д', 'Д', false],
  Semicolon: [true, ';', ':', 'ж', 'Ж', false],
  Quote: [true, '\'', '"', 'э', 'Э', false],
  Enter: [false, 'Enter       ', 'Enter       ', 'Enter       ', 'Enter       ', false],
  ShiftLeft: [false, 'Shift           ', 'Shift          ', 'Shift           ', 'Shift           ', false],

  KeyZ: [true, 'z', 'Z', 'я', 'Я', false],
  KeyX: [true, 'x', 'X', 'ч', 'Ч', false],
  KeyC: [true, 'c', 'C', 'с', 'С', false],
  KeyV: [true, 'v', 'V', 'м', 'М', false],
  KeyB: [true, 'b', 'B', 'и', 'И', false],
  KeyN: [true, 'n', 'N', 'т', 'Т', false],
  KeyM: [true, 'm', 'M', 'ь', 'Ь', false],
  Comma: [true, ',', '<', 'б', 'Б', false],
  Period: [true, '.', '>', 'ю', 'Ю', false],
  Slash: [true, '/', '?', '.', ',', false],
  ShiftRight: [false, '⇧', '⇧', '⇧', '⇧', false],
  ArrowUp: [false, '↑', '↑', '↑', '↑', false],
  Language: [false, 'EN', 'EN', 'RU', 'RU', false],

  ControlLeft: [false, 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl', false],
  MetaLeft: [false, 'Win', 'Win', 'Win', 'Win', false],
  AltLeft: [false, 'Alt', 'Alt', 'Alt', 'Alt', false],
  Space: [false, 'Space', 'Space', 'Space', 'Space', false],
  AltRight: [false, 'Alt', 'Alt', 'Alt', 'Alt', false],
  ControlRight: [false, 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl', false],
  ArrowLeft: [false, '←', '←', '←', '←', false],
  ArrowDown: [false, '↓', '↓', '↓', '↓', false],
  ArrowRight: [false, '→', '→', '→', '→', false],
};

const KEYBOARD_KEYS = [
  'Backquote',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Minus',
  'Equal',
  'Backspace',
  'Tab',

  'KeyQ',
  'KeyW',
  'KeyE',
  'KeyR',
  'KeyT',
  'KeyY',
  'KeyU',
  'KeyI',
  'KeyO',
  'KeyP',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'Delete',
  'CapsLock',

  'KeyA',
  'KeyS',
  'KeyD',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyJ',
  'KeyK',
  'KeyL',
  'Semicolon',
  'Quote',
  'Enter',
  'ShiftLeft',

  'KeyZ',
  'KeyX',
  'KeyC',
  'KeyV',
  'KeyB',
  'KeyN',
  'KeyM',
  'Comma',
  'Period',
  'Slash',
  'ShiftRight',
  'ArrowUp',
  'Language',

  'ControlLeft',
  'MetaLeft',
  'AltLeft',
  'Space',
  'AltRight',
  'ControlRight',
  'ArrowLeft',
  'ArrowDown',
  'ArrowRight',
];

export {
  KEYS_MAP,
  KEYBOARD_KEYS,
};
